# Generated by Django 5.2 on 2026-02-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaching',
            options={'ordering': ['start_at'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('title', 'start_at')},
        ),
    ]
