# Generated by Django 5.2 on 2026-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0002_alter_teaching_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaching',
            options={'ordering': ['start_at']},
        ),
        migrations.AlterField(
            model_name='teaching',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='duracion_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='start_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
