"""
Django settings for FrameffX project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Carga las variables de entorno desde el archivo .env si está disponible
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-qrd!o)c7y#7m=e3qkkhpuu^ffr7$lu!e75llb+(y+3*2+s6#=7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'ads',
    'bookings',
    'login',
    'teachings',
    'common',
    'users',
    'products',
    'crispy_forms',
    'crispy_bootstrap5',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',   # Proveedor de Google OAuth
    'djoser',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'FrameffX.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
           'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    # Habilita el login mediante username en el panel de administración de Django
    'django.contrib.auth.backends.ModelBackend',

    # Habilita el login mediante email a través de django-allauth
    'allauth.account.auth_backends.AuthenticationBackend',
)

WSGI_APPLICATION = 'FrameffX.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.postgresql':
    # Base de datos PostgreSQL para entornos de producción
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DB_NAME', 'frameffx_db'),
            'USER': os.getenv('DB_USER', 'frameffx_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # Base de datos SQLite para entornos de desarrollo local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Directorio destino de collectstatic (producción)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Directorio donde Django busca los archivos estáticos del proyecto
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Configuración de email

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = os.getenv('SERVER_EMAIL', EMAIL_HOST_USER)


# Ajustes de seguridad activos únicamente en producción (cuando DEBUG es False)

if not DEBUG:
    # Necesario para que Django sepa que la petición original era HTTPS
    # cuando corre detrás de un proxy inverso (Nginx). Sin esto,
    # SECURE_SSL_REDIRECT causa un bucle infinito de redirecciones.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
    SECURE_BROWSER_XSS_FILTER = os.getenv('SECURE_BROWSER_XSS_FILTER', 'False') == 'True'
    SECURE_CONTENT_SECURITY_POLICY = os.getenv('SECURE_CONTENT_SECURITY_POLICY', 'False') == 'True'
    X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

    # Requerido por Django 4.0+ para aceptar peticiones POST desde HTTPS a través de Nginx.
    # Sin esto, el middleware CSRF bloquea todos los formularios en producción.
    _allowed_hosts = os.getenv('ALLOWED_HOSTS', '')
    CSRF_TRUSTED_ORIGINS = [
        f'https://{h.strip()}' for h in _allowed_hosts.split(',') if h.strip()
    ]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.Usuario'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Rutas de redirección tras el inicio y cierre de sesión
LOGIN_REDIRECT_URL = '/'      # Redirige a la raíz, donde LandingView enruta al marketplace
LOGIN_URL = '/login/'


# Configuración de allauth y Google OAuth 2.0

# Comportamiento general de allauth
ACCOUNT_AUTHENTICATION_METHOD = 'email'   # Usa el email como método de autenticación
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False          # El modelo Usuario no utiliza username
# En producción se requiere verificación de email para evitar registros fraudulentos.
# En desarrollo se deja opcional para facilitar las pruebas.
ACCOUNT_EMAIL_VERIFICATION = 'optional' if DEBUG else 'mandatory'
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http' if DEBUG else 'https'  # HTTP en local, HTTPS en producción

# Configuración del proveedor de Google
# Las credenciales (CLIENT_ID y SECRET) no se almacenan en código fuente.
# Se cargan desde el archivo .env o se configuran en el panel de Django Admin
# (Sites > Social Applications).
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # Scopes mínimos requeridos: perfil básico y email
        'SCOPE': [
            'profile',
            'email',
        ],
        # Solicita el email en cada autorización, aunque el usuario ya haya autorizado previamente
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',    # Muestra el selector de cuentas de Google
        },
        # Las credenciales OAuth se configuran desde el Admin de Django
        'OAUTH_PKCE_ENABLED': False,
    }
}

# Inicia la sesión directamente al hacer clic en el enlace OAuth sin pantalla de confirmación intermedia
SOCIALACCOUNT_LOGIN_ON_GET = True

# Vincula la cuenta social al usuario existente si el email ya está registrado localmente
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True


# Configuración de Stripe
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_tymock')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_tymock')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_tymock')

# Configuración de API REST (DRF y Simple JWT)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'allauth': {
            'handlers': ['console'],
            # DEBUG en desarrollo para facilitar el diagnóstico de OAuth.
            # WARNING en producción para evitar saturar los logs con información sensible.
            'level': 'DEBUG' if DEBUG else 'WARNING',
        },
    },
}

