"""
Django settings for FrameffX project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file (opcional)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-qrd!o)c7y#7m=e3qkkhpuu^ffr7$lu!e75llb+(y+3*2+s6#=7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'ads',
    'bookings',
    'teachings',
    'common',
    'users',
    'products',
    'crispy_forms',
    'crispy_bootstrap5',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',   # ← Proveedor de Google OAuth
    'djoser',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'FrameffX.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
           'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    # Necesaria para realizar el login usando username en el 
    # administrador de Django, independiente de django allauth
    'django.contrib.auth.backends.ModelBackend',

    # métodos de autenticación especifica, como por ejemplo email
    'allauth.account.auth_backends.AuthenticationBackend',
)

WSGI_APPLICATION = 'FrameffX.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.postgresql':
    # PostgreSQL (Producción)
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DB_NAME', 'frameffx_db'),
            'USER': os.getenv('DB_USER', 'frameffx_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # SQLite (Desarrollo)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Donde collectstatic copia TODO (producción)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Donde Django busca tus static originales
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email Configuration
# https://docs.djangoproject.com/en/5.2/topics/email/

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')


# Security Settings
# https://docs.djangoproject.com/en/5.2/topics/security/

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
    SECURE_BROWSER_XSS_FILTER = os.getenv('SECURE_BROWSER_XSS_FILTER', 'False') == 'True'
    SECURE_CONTENT_SECURITY_POLICY = os.getenv('SECURE_CONTENT_SECURITY_POLICY', 'False') == 'True'
    X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.Usuario'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Redirects de autenticación
LOGIN_REDIRECT_URL = '/'      # Redirige a la raíz para que LandingView enrute al Marketplace
LOGIN_URL = '/login/'


# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURACIÓN DE ALLAUTH Y GOOGLE OAUTH 2.0
# ─────────────────────────────────────────────────────────────────────────────

# Comportamiento general de allauth
ACCOUNT_AUTHENTICATION_METHOD = 'email'   # Login por email, no por username
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False          # El modelo Usuario no usa username
ACCOUNT_EMAIL_VERIFICATION = 'optional'    # Cambiar a 'mandatory' en producción
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'    # Fuerza HTTPS en emails de allauth

# Configuración del proveedor de Google
# Las credenciales (CLIENT_ID y SECRET) NUNCA deben estar en código fuente.
# Déjalas en blanco aquí: se cargan desde el .env o se configuran directamente
# en el panel de Django Admin (Sites > Social Applications > Añadir).
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # Scopes mínimos necesarios: perfil básico + email
        'SCOPE': [
            'profile',
            'email',
        ],
        # Solicita siempre el email aunque el usuario ya haya autorizado antes
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        # Las credenciales se gestionan desde el Admin de Django (método seguro)
        # o se pueden definir aqui para entornos de desarrollo:
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret':    os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key':       '',
        },
        'OAUTH_PKCE_ENABLED': True,    # Habilita PKCE para mayor seguridad
    }
}

# Evita crear cuentas duplicadas si el email ya existe en la BD local
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True


# ─────────────────────────────────────────────────────────────────────────────
# STRIPE CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_tymock')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_tymock')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_tymock')

